// Generated by nuxi
/// <reference types="@pinia/nuxt" />
/// <reference types="@pinia-plugin-persistedstate/nuxt" />
/// <reference types="@vite-pwa/nuxt" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vite/client" />
/// <reference types="@pinia/nuxt" />
/// <reference path="../node_modules/@vite-pwa/nuxt/dist/runtime/plugins/types" />
/// <reference types="@vite-pwa/nuxt/configuration" />
/// <reference types="vite-plugin-pwa/vue" />
/// <reference types="vite-plugin-pwa/info" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="nuxt-config-schema" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
